name: open_meteo_api
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.7

flutter: null
