name: weather_repository
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  coverage: ^1.9.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2
  json_annotation: ^4.9.0
  open_meteo_api:
    publish_to: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.7

flutter: null
